### PR TITLE
Fix a load of random errors

### PR DESCRIPTION
**Pull request by John-Fries-J**
If you use Axe Leaf Veinminer & Axe Drop To Inventory it causes major server lag. Editing this so you don't have Veinminer and Axe Drop To Inventory at the same time fixes any issues with server lag.

### CODE REVIEW

**Comment by John-Fries-J** [comment]
Added a fix for levels being added to the lore randomly causing a 1 to appear.

**Comment by John-Fries-J** [comment]
Fix random capitalizations in the lore of multi armor

**Comment by John-Fries-J** [comment]
Fixed the titles of all the skill types.

**Comment by NextdoorPsycho** [comment]
My Eternal Gratitude. <3

**Pull request merged**
