### PR TITLE
Added reload functionality

### PR DESCRIPTION
**Pull request by rafaelflromao**

### CODE REVIEW

**Comment by rafaelflromao** [comment]
Sorry, I forgot to switch to the other branch

**Comment by NextdoorPsycho** [comment]
Does not work, 
This needs to reload the Master adapt.json, and not cause a reload loop lol. try it.

**Comment by rafaelflromao** [comment]
> Does not work, This needs to reload the Master adapt.json, and not cause a reload loop lol. try it.

Sorry I didn't see the FileWatcher.

**Comment by NextdoorPsycho** [comment]
All good! If you fix it let me know and I'll merge it.

**Pull request merged**
