### PR TITLE
Adding CI/CD

### PR DESCRIPTION
**Pull request by illyrius666**
- [ ] Adding a ci/cd that will build and release artifact on merge with main. @CrazyDev05 i added the base template, it still needs to be finetuned based on what adapt needs specifically. we also need to setup secrets.

### CODE REVIEW

**Comment by illyrius666** [comment]
we could extend it to also automatically release on spigot/etc

**Comment by CrazyDev05** [comment]
> we could extend it to also automatically release on spigot/etc

spigotmc forbids third party api usage

**Comment by illyrius666** [comment]
> > we could extend it to also automatically release on spigot/etc
> 
> spigotmc forbids third party api usage

really, phow that sucks...

**Comment by AvianAeternum** [comment]
I wouldnt want it to release to spigot automagically anyways, there are specific release times that perform better.

**Pull request merged**
