### PR TITLE
Development: 1.16.0-1.19.2-1.21.3

### PR DESCRIPTION
**Pull request by CrazyDev05**
Changes:
- [x] Fix Broken Messages
- [x] Add option for Welcome Message
- [x] allow minimessage coloring in localization
- [x] reuse inventories for guis if possible #508 
- [x] Custom model data for gui items and advancments #491 
- [x] Silktouch Spawner skill #505
- [x] 1.21.3 Support
- [x] add missing advancement translations
- [x] automatic gradient generation #510 
- [x] Enderveil skill #329 

Translation chnages:
```json
{
  "advancement": {
    "challenge_eat_100": {
      "title": "So much to eat!",
      "description": "Eat over 100 Items!"
    },
    "challenge_eat_1000": {
      "title": "Unquenchable Hunger!",
      "description": "Eat over 1,000 Items!"
    },
    "challenge_eat_10000": {
      "title": "EVERLASTING HUNGER!",
      "description": "Eat over 10,000 Items!"
    },
    "challenge_harvest_100": {
      "title": "Full Harvest",
      "description": "Harvest over 100 crops!"
    },
    "challenge_harvest_1000": {
      "title": "Grand Harvest",
      "description": "Harvest over 1,000 crops!"
    },
    "challenge_swim_1nm": {
      "title": "Human Submarine!",
      "description": "Swim 1 Nautical Mile (1,852 blocks)"
    },
    "challenge_sneak_1k": {
      "title": "Knee Pain",
      "description": "Sneak over a kilometer (1,000 blocks)"
    }
  },
  "pickaxe": {
    "silkspawner": {
      "name": "Pickaxe Silk-Spawner",
      "description": "Makes Spawners drop when broken",
      "lore1": "Makes Spawners breakable with silk touch.",
      "lore2": "Makes Spawners breakable while sneaking."
    }
  },
  "stealth": {
    "enderveil": {
      "name": "Enderveil",
      "description": "No more Pumpkins to prevent Enderman attacks",
      "lore1": "Prevent enderman attacks while sneaking",
      "lore2": "Prevent all enderman attacks"
    }
  }
}
```

### CODE REVIEW

**Comment by illyrius666** [comment]
LETSGOOOO

**Comment by illyrius666** [comment]
@CrazyDev05 i just builded from the latest development commit and it throws some errors on glowingentities:
`[15:37:56 INFO]: [Adapt]: Language: en_US - Language Fallback: en_US
[15:37:57 INFO]: [Adapt]: 
 █████╗ ██████╗  █████╗ ██████╗ ████████╗
██╔══██╗██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝         Version: 1.15.3-1.19.2-1.21.3     
███████║██║  ██║███████║██████╔╝   ██║            By: Arcane Arts (Volmit Software)
██╔══██║██║  ██║██╔══██║██╔═══╝    ██║            Java Version: 21     
██║  ██║██████╔╝██║  ██║██║        ██║   
╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝        ╚═╝   

[15:37:58 INFO]: [Adapt]: Checking for updates...
[15:37:58 INFO]: [Adapt]: Please update your Adapt plugin to the latest version! (Current: 1.15.3-1.19.2-1.21.3 Latest: 1.15.2-1.19.2-1.21.1)
[15:37:58 INFO]: [GlowingEntities] [GlowingEntities] Found server version 1.21.3
[15:37:58 INFO]: [GlowingEntities] [GlowingEntities] Loaded transparent mappings.
[15:37:58 ERROR]: [GlowingEntities] [GlowingEntities] Glowing Entities reflection failed to initialize. The util is disabled. Please ensure your version (1.21.3-R0.1-SNAPSHOT) is supported.
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities.<init>(GlowingEntities.java:58) ~[?:?]
        at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.Adapt.start(Adapt.java:148) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
        at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.util.VolmitPlugin.onEnable(VolmitPlugin.java:68) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.paperConfig()" because "world" is null
        at net.minecraft.world.entity.Entity.<init>(Entity.java:574) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.world.entity.Marker.<init>(Marker.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        ... 22 more
[15:37:58 ERROR]: Error occurred while enabling Adapt v1.15.3-1.19.2-1.21.3 (Is it up to date?)
java.lang.IllegalStateException: The Glowing Entities API is disabled. An error has occured during first initialization.
        at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:369) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities.<init>(GlowingEntities.java:58) ~[?:?]
        at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.Adapt.start(Adapt.java:148) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
        at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.util.VolmitPlugin.onEnable(VolmitPlugin.java:68) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
        ... 15 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.paperConfig()" because "world" is null
        at net.minecraft.world.entity.Entity.<init>(Entity.java:574) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.world.entity.Marker.<init>(Marker.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
        at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
        ... 15 more
[15:37:58 INFO]: [Adapt] Disabling Adapt v1.15.3-1.19.2-1.21.3
[15:37:58 ERROR]: Error occurred while disabling Adapt v1.15.3-1.19.2-1.21.3
java.lang.NullPointerException: Cannot invoke "fr.skytasul.glowingentities.GlowingEntities.disable()" because "this.glowingEntities" is null
        at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.Adapt.stop(Adapt.java:181) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
        at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.util.VolmitPlugin.onDisable(VolmitPlugin.java:107) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by CrazyDev05** [comment]
> @CrazyDev05 i just built from the latest development commit and it throws some errors on glowingentities:
> 
> ```
> `[15:37:56 INFO]: [Adapt]: Language: en_US - Language Fallback: en_US
> [15:37:57 INFO]: [Adapt]: 
>  █████╗ ██████╗  █████╗ ██████╗ ████████╗
> ██╔══██╗██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝         Version: 1.15.3-1.19.2-1.21.3     
> ███████║██║  ██║███████║██████╔╝   ██║            By: Arcane Arts (Volmit Software)
> ██╔══██║██║  ██║██╔══██║██╔═══╝    ██║            Java Version: 21     
> ██║  ██║██████╔╝██║  ██║██║        ██║   
> ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝        ╚═╝   
> 
> [15:37:58 INFO]: [Adapt]: Checking for updates...
> [15:37:58 INFO]: [Adapt]: Please update your Adapt plugin to the latest version! (Current: 1.15.3-1.19.2-1.21.3 Latest: 1.15.2-1.19.2-1.21.1)
> [15:37:58 INFO]: [GlowingEntities] [GlowingEntities] Found server version 1.21.3
> [15:37:58 INFO]: [GlowingEntities] [GlowingEntities] Loaded transparent mappings.
> [15:37:58 ERROR]: [GlowingEntities] [GlowingEntities] Glowing Entities reflection failed to initialize. The util is disabled. Please ensure your version (1.21.3-R0.1-SNAPSHOT) is supported.
> java.lang.reflect.InvocationTargetException: null
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
>         at fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities.<init>(GlowingEntities.java:58) ~[?:?]
>         at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.Adapt.start(Adapt.java:148) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
>         at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.util.VolmitPlugin.onEnable(VolmitPlugin.java:68) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.paperConfig()" because "world" is null
>         at net.minecraft.world.entity.Entity.<init>(Entity.java:574) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.world.entity.Marker.<init>(Marker.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         ... 22 more
> [15:37:58 ERROR]: Error occurred while enabling Adapt v1.15.3-1.19.2-1.21.3 (Is it up to date?)
> java.lang.IllegalStateException: The Glowing Entities API is disabled. An error has occured during first initialization.
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:369) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities.<init>(GlowingEntities.java:58) ~[?:?]
>         at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.Adapt.start(Adapt.java:148) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
>         at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.util.VolmitPlugin.onEnable(VolmitPlugin.java:68) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
>         at fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
>         ... 15 more
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.paperConfig()" because "world" is null
>         at net.minecraft.world.entity.Entity.<init>(Entity.java:574) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.world.entity.Marker.<init>(Marker.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
>         at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
>         at fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
>         at fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
>         ... 15 more
> [15:37:58 INFO]: [Adapt] Disabling Adapt v1.15.3-1.19.2-1.21.3
> [15:37:58 ERROR]: Error occurred while disabling Adapt v1.15.3-1.19.2-1.21.3
> java.lang.NullPointerException: Cannot invoke "fr.skytasul.glowingentities.GlowingEntities.disable()" because "this.glowingEntities" is null
>         at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.Adapt.stop(Adapt.java:181) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
>         at Adapt-1.15.3-1.19.2-1.21.3.jar/com.volmit.adapt.util.VolmitPlugin.onDisable(VolmitPlugin.java:107) ~[Adapt-1.15.3-1.19.2-1.21.3.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
>         at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]`
> ```

love it when devs don't test thier shit https://github.com/SkytAsul/GlowingEntities/releases/tag/1.4.1

**Comment by CrazyDev05** [comment]
@illyrius666 what Minecraft version are you on, so i can properly report it?

**Comment by illyrius666** [comment]
> @illyrius666 what Minecraft version are you on, so i can properly report it?

```
version
[15:54:13 INFO]: Checking version, please wait...
[15:54:13 INFO]: This server is running Paper version 1.21.3-81-master@da71382 (2024-12-03T14:58:13Z) (Implementing API version 1.21.3-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.3-80-c2294d7 (MC: 1.21.3)
> 
```

**Comment by CrazyDev05** [comment]
@illyrius666 try again now
_this definitely wasn't my fault 🫠_

**Comment by illyrius666** [comment]
> @illyrius666 try again now _this definitely wasn't my fault 🫠_

everything works fine now!

**Pull request merged**
